config/routes.rb
Lab5::Application.routes.draw do
   
  get "menu/form"
  
  get "menu/info"

  get "menu/home"

  root :to => 'menu#home'
  match '/form' => 'menu#form'
  match '/veg' => 'menu#info'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def home
  	def form
  		def info
  		end
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lab5</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/menu/denied.html.erb
<p>
Access denied! </br>
Please recheck your username and password
</p>

app/views/menu/form.html.erb
<h1>Please Fill out my form :) !!!</h1>

<%=form_tag do %>
</br>
<%=label_tag(:body, "Please enter your log in details:")%> </br></br>
	<%=label_tag(:body, "Username:")%> 
	<%=text_field_tag(:body)%> </br>
	<%=label_tag(:body, "Password:")%>
	<%=text_field_tag(:body)%> </br></br>
	<%=submit_tag("Submit")%> 

	<%end%>

<p>Find me in app/views/menu/form.html.erb</p>

app/views/menu/granted.html.erb
<p>
Access granted! </br>
WELCOME :D
</p>

app/views/menu/home.html.erb
<h1>Welcome :)!!!</h1>
</br>
<%= link_to "My Form :)", form_path(@form) %>
</br></br>
<%= link_to "My other Form", veg_path(@info) %>
</br></br></br>

app/views/menu/info.html.erb
</br></br>
<p><b>Menu :) </b></p></br>
<p>Are you a Vegetarian? </p>

<p><%=radio_button_tag(:veg,"Vegetarian")%> YES</p>
<p><%=radio_button_tag(:nonveg,"Non-Vegetarian")%> NO</p>
</br>
<p>What are your favourite sports? (Please choose more than 1) </p>
<p><%=check_box_tag(:sport)%> Soccer</p>
<p><%=check_box_tag(:sport)%> Hurling</p>
<p><%=check_box_tag(:sport)%> Rugby</p>
<p><%=check_box_tag(:sport)%> Gaelic Football</p>
<p><%=check_box_tag(:sport)%> Cricket</p>
</br>
<%=submit_tag("Submit")%> 